### ISSUE TITLE
WARP Charge Tracker can't save "Briefkopf" 

### ISSUE THREAD

**Issue by batti** [Tinkerforge/esp32-firmware#375] opened 2024-10-08 13:51 UTC
Firmware 2.6.1

If I enter a Briefkopf, "Speichern" button will not be activated.
Also it seems that the data is not saved.

**Comment by rtrbt** [comment] 2024-10-08 13:53
Duplicate of https://github.com/Tinkerforge/esp32-firmware/issues/262

**Closed by rtrbt** 2024-10-08 13:53 UTC
Labels: bug
