### ISSUE TITLE
show new firmware available

### ISSUE THREAD

**Issue by breitsi** [Tinkerforge/esp32-firmware#237] opened 2023-05-04 09:56 UTC
Notify if a new Firmware is available (somehow somewhere) 
It would be nice to update with one click without download the firmware manually

**Comment by rtrbt** [comment] 2023-05-04 10:12
Duplicate of https://github.com/Tinkerforge/esp32-firmware/issues/88.

**Closed by rtrbt** 2023-05-04 10:12 UTC
